language: php
php:
 - 5.5
 - 5.4
 - 5.3
before_script:
 - composer install
script:
 - mkdir -p build/logs
 - vendor/bin/phpunit -c test/config/unit-tests.xml
 - vendor/bin/phpunit -c test/config/unit-tests.xml --coverage-clover build/logs/clover.xml

after_script:
 - vendor/bin/coveralls -v